---
- name: check whether grub is installed
  stat:
    path: /usr/sbin/update-grub
  register: grub_installed_result

- name: manage grub
  template:
    src: grub.j2
    dest: /etc/default/grub
  when: grub_installed_result.stat.exists
  notify:
    - update grub
