---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    image: ubuntu:18.04
  - name: focal
    image: ubuntu:20.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    D: true
verifier:
  name: testinfra
