---
- name: manage mike's account
  user:
    name: mike
    home: "{{ users_home_root}}/mike"
    groups:
      - sudo
    append: true

- name: manage mike's SSH authorized_keys
  authorized_key:
    user: mike
    key: "{{ item }}"
  loop: "{{ users_authorized_keys }}"

- include_role:
    name: attic
  when: users_attic_backup

- name: manage attic cron job
  become: true
  become_user: mike
  cron:
    name: attic_backup_mail.conigliaro.org
    hour: '*/12'
    minute: 0
    job: chronic /usr/local/bin/attic_backup mail.conigliaro.org /mnt/data/mike/Maildir
  when: users_attic_backup

- name: manage .dovecot.sieve
  become: true
  become_user: mike
  template:
    src: .dovecot.sieve.j2
    dest: "{{ users_home_root }}/mike/.dovecot.sieve"
  notify:
    - sievec
  when: users_dovecot_sieve
