---
- name: manage mike's account
  user:
    name: mike
    home: "{{ users_home_root}}/mike"
    groups:
      - sudo
    append: true

- name: manage mike's SSH authorized_keys
  authorized_key:
    user: mike
    key: "{{ item }}"
  loop: "{{ users_authorized_keys }}"

- name: Manage attic cron job
  become: true
  become_user: mike
  cron:
    name: attic_backup_mail.conigliaro.org
    minute: '*/12'
    job: chronic /usr/local/bin/attic_backup mail.conigliaro.org /mnt/data/mike/Maildir
  when: users_attic_backup
