---
- name: manage mike's account
  user:
    name: mike
    home: "{{ users_home_root }}/mike"
    groups:
      - sudo
    append: true

- name: manage mike's SSH authorized_keys
  authorized_key:
    user: mike
    key: "{{ item }}"
  loop: "{{ users_authorized_keys }}"

- include_role:
    name: borgbackup
  when: users_borgbackup_enabled

- name: check whether borg repository exists
  become: true
  become_user: mike
  stat:
    path: mail.conigliaro.org.borg
  register: borg_repository_stat_result
  when: users_borgbackup_enabled

- name: initialize borg repository
  become: true
  become_user: mike
  command: borg init --encryption=none mail.conigliaro.org.borg
  when: users_borgbackup_enabled and not borg_repository_stat_result.stat.exists

- name: manage borg cron job
  become: true
  become_user: mike
  cron:
    name: borg_backup_mail.conigliaro.org
    hour: '*/12'
    minute: '0'
    job: chronic /usr/local/bin/borg_backup mail.conigliaro.org /mnt/data/mike/Maildir
  when: users_borgbackup_enabled

- name: manage .dovecot.sieve
  become: true
  become_user: mike
  template:
    src: .dovecot.sieve.j2
    dest: "{{ users_home_root }}/mike/.dovecot.sieve"
  notify:
    - sievec
  when: users_dovecot_sieve
