# Installs `brew services` commands
tap 'homebrew/services'

# Provides alternate versions of casks
tap 'caskroom/versions'

# Provides access to ‘drivers’
tap 'caskroom/drivers'

# Dependencies
cask 'java'
cask 'xquartz'

# Packages
brew 'antigen'
cask 'appcleaner'
brew 'asdf'
cask 'authy'
brew 'awscli'
brew 'bfg'
cask 'chef/chef/chefdk'
cask 'clover-configurator'
cask 'colloquy'
brew 'coreutils'
cask 'cyberduck'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'gimp'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
cask 'google-chrome'
brew 'gpg'
brew 'hadolint'
cask 'handbrake'
brew 'htop'
cask 'iterm2-beta'
brew 'jq'
cask 'jsl'
brew 'mtr'
brew 'nmap'
cask 'openemu'
brew 'packer'
brew 'pinentry-mac'
cask 'postman'
brew 'pssh'
brew 'pwgen'
brew 'rename'
cask 'sequel-pro'
brew 'shellcheck'
cask 'slack'
cask 'sonos'
cask 'spideroakone'
brew 'squid'
brew 'stow'
cask 'sublime-text'
brew 'telnet'
brew 'terraform'
brew 'the_silver_searcher'
cask 'the-unarchiver'
brew 'tor'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
brew 'watch'
brew 'wget'
cask 'wireshark'
brew 'write-good'
brew 'yamllint'
brew 'zsh'
