#!/usr/bin/env bash
#
# Usage: ./run-chef <role>
#
set -eu

ROLE=$1
LSB_ID=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
LSB_RELEASE=$(lsb_release -sr)
CHEF_VERSION=13.0.118
CHEF_PACKAGE=chef_${CHEF_VERSION}-1_amd64.deb
CHEF_URL=https://packages.chef.io/files/stable/chef/${CHEF_VERSION}/${LSB_ID}/${LSB_RELEASE}/${CHEF_PACKAGE}

if ! command -v chef-solo >/dev/null 2>&1; then
  wget -O /tmp/${CHEF_PACKAGE} -c "$CHEF_URL"
  sudo dpkg -i /tmp/${CHEF_PACKAGE}
fi

sudo chef-solo --config solo.rb --override-runlist "role[$ROLE]" --json-attributes "json_attributes/${ROLE}.json"
