name 'mconigliaro_ubuntu'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_ubuntu'
long_description 'Installs/Configures mconigliaro_ubuntu'
version '0.1.0'
