---
- name: install dovecot lmtp
  apt:
    name:
      - dovecot-lmtpd

- name: configure dovecot lmtp
  template:
    src: 20-lmtp.override.conf.j2
    dest: /etc/dovecot/conf.d/20-lmtp.override.conf
  notify: restart dovecot
