---
- name: install dovecot
  apt:
    name: dovecot-common

- name: configure dovecot ssl
  template:
    src: 99-ssl.conf.j2
    dest: /etc/dovecot/conf.d/99-ssl.conf
  notify: restart dovecot

- name: configure monit for dovecot
  template:
    src: dovecot.monit.j2
    dest: /etc/monit/conf.d/dovecot
  notify:
    - restart monit

- import_tasks: auth.yml
  when: dovecot_configure_auth

- import_tasks: imap.yml
  when: dovecot_configure_imap

- name: start dovecot
  service:
    name: dovecot
    state: started
