---
- name: install dovecot
  apt:
    name: dovecot-common

- name: configure dovecot
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  loop:
    - 10-mail.override.conf
    - 10-ssl.override.conf
  notify: restart dovecot

- import_tasks: auth.yml
  when: dovecot_configure_auth

- import_tasks: imap.yml
  when: dovecot_configure_imap

- import_tasks: lmtp.yml
  when: dovecot_configure_lmtp

- import_tasks: sieve.yml
  when: dovecot_configure_sieve

- name: start dovecot
  service:
    name: dovecot
    state: started

- name: configure monit for dovecot
  template:
    src: dovecot.monit.j2
    dest: /etc/monit/conf.d/dovecot
  notify:
    - restart monit
