---
- name: install dovecot
  apt:
    name:
      - dovecot-common
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-sieve

- name: configure dovecot
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  loop:
    - 10-auth.override.conf
    - 10-mail.override.conf
    - 10-ssl.override.conf
    - 20-imap.override.conf
    - 20-lmtp.override.conf
    - 90-sieve.override.conf
  notify: restart dovecot

- name: create sieve_before directory
  file:
    path: /var/lib/dovecot/sieve_before.d
    state: directory

- name: manage sieve_before scripts
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/dovecot/sieve_before.d/{{ item }}"
  loop:
    - 10-junk.sieve
  notify: sievec_sieve_before

- name: "manage {{ user_username }}'s .dovecot.sieve"
  become: true
  become_user: "{{ user_username }}"
  template:
    src: .dovecot.sieve.j2
    dest: "{{ user_home_root }}/{{ user_username }}/.dovecot.sieve"
  notify:
    - user_sievec

- name: start dovecot
  service:
    name: dovecot
    state: started

- name: configure monit for dovecot
  template:
    src: dovecot.monit.j2
    dest: /etc/monit/conf.d/dovecot
  notify:
    - restart monit
