name 'mconigliaro_sysstat'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_sysstat'
long_description 'Installs/Configures mconigliaro_sysstat'
version '0.1.0'
