---
- name: Install monit
  apt:
    name: monit

- name: Configure monit
  template:
    src: templates/monitrc.j2
    dest: /etc/monit/monitrc
    mode: 0600
  notify:
    - Restart monit

- name: Start monit
  service:
    name: monit
    state: started
