---
- name: install monit
  apt:
    name: monit

- name: configure monit
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    mode: 0600
  notify:
    - restart monit

- name: start monit
  service:
    name: monit
    state: started
