---
- name: Converge
  hosts: all
  roles:
    - role: block_devices
    - role: data_volumes
  vars:
    block_devices:
      -
        file: /tmp/test0
        size: 10
        device: /dev/loop0
      -
        file: /tmp/test1
        size: 20
        device: /dev/loop1
      -
        file: /tmp/test2
        size: 30
        device: /dev/loop2
    data_volumes:
      -
        device: /dev/loop0
        path: /mnt/test0
      -
        device: /dev/loop1
        path: /mnt/test1
      -
        device: /dev/loop2
        path: /mnt/test2
