name 'mconigliaro_sudo'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_sudo'
long_description 'Installs/Configures mconigliaro_sudo'
version '0.1.0'
