---
- name: configure motd-news
  template:
    src: motd-news.j2
    dest: /etc/default/motd-news

- name: install default packages
  apt:
    name:
      - bsd-mailx
      - curl
      - htop
      - lsof
      - mtr-tiny
      - psmisc
      - silversearcher-ag
      - strace
      - tcpdump
      - telnet
      - tmux
      - usbmount
      - vim
