---
- include_role:
    name: rspamd
  when: postfix_configure_rspamd

- name: install postfix
  apt:
    name: postfix

- name: manage mailname
  template:
    src: mailname.j2
    dest: /etc/mailname
  notify:
    - stop postfix
    - restart postfix

- name: manage master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
  notify:
    - stop postfix
    - restart postfix

- name: manage main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify:
    - stop postfix
    - restart postfix

- name: manage alias maps
  template:
    src: aliases.j2
    dest: /etc/aliases
  notify: run newaliases

- name: manage SASL password maps
  copy:
    content: "{{ postfix_conf_sasl_password_maps | join(\"\n\") }}"
    dest: /etc/postfix/sasl_password
  notify: run postmap on SASL password maps

- name: manage virtual alias maps
  copy:
    content: "{{ postfix_conf_virtual_maps | join(\"\n\") }}"
    dest: /etc/postfix/virtual
  notify: run postmap on virtual alias maps

- name: manage access_sender maps
  copy:
    content: "{{ postfix_conf_access_sender | join(\"\n\") }}"
    dest: /etc/postfix/access_sender
  notify: run postmap on access_sender maps

- name: start postfix
  service:
    name: postfix
    state: started

- name: configure monit for postfix
  template:
    src: postfix.monit.j2
    dest: /etc/monit/conf.d/postfix
  notify:
    - restart monit
