---
- name: Install postfix
  apt:
    name: postfix

- name: Start postfix
  service:
    name: postfix
    state: started
  when: ansible_virtualization_type != "docker"

- name: Manage mailname
  template:
    src: mailname.j2
    dest: /etc/mailname
  notify:
    - Restart postfix

- name: Manage master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
  notify:
    - Restart postfix

- name: Manage main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify:
    - Restart postfix

- name: Manage alias maps
  template:
    src: aliases.j2
    dest: /etc/aliases
  notify: Run newaliases

- name: Manage SASL password maps
  copy:
    content: "{{ postfix_conf_sasl_password_maps | join(\"\n\") }}"
    dest: /etc/postfix/sasl_password
  notify: Run postmap on SASL password maps

- name: Manage virtual alias maps
  copy:
    content: "{{ postfix_conf_virtual_maps | join(\"\n\") }}"
    dest: /etc/postfix/virtual
  notify: Run postmap on virtual alias maps

- name: Configure monit for postfix
  template:
    src: postfix.monit.j2
    dest: /etc/monit/conf.d/postfix
  notify:
    - Restart monit

- import_tasks: amavis.yml
  when: postfix_configure_amavis

- import_tasks: postgrey.yml
  when: postfix_configure_postgrey
