---
- name: check block devices
  stat:
    path: "{{ item.file }}"
  loop: "{{ block_devices }}"
  register: block_devices_stat

- name: create block device files
  command: |
      dd if=/dev/zero of={{ item.item.file }}
      bs={{ ('block_size' in item.item) | ternary(item.item.block_size, '1M') }}
      count={{ ('size' in item.item) | ternary(item.item.size, 1) }}
  loop: "{{ block_devices_stat.results }}"
  when: not item.stat.exists

- name: check whether block devices are used
  command: losetup {{ item.device }}
  register: losetup_result
  changed_when: false
  ignore_errors: true
  loop: "{{ block_devices }}"

- name: create block devices
  command: losetup {{ item.item.device }} {{ item.item.file }}
  when: item.failed
  loop: "{{ losetup_result.results }}"
