---
- name: check whether block devices exists
  stat:
    path: "{{item.device}}"
  loop: "{{block_devices}}"
  register: block_devices_stat_result

- name: create block devices
  command: dd if=/dev/zero of={{item.item.device}} bs={{ ('block_size' in item.item) | ternary(item.item.block_size, '1M') }} count={{ ('size' in item.item) | ternary(item.item.size, 1) }}
  loop: "{{block_devices_stat_result.results}}"
  when: item.stat.exists != True
