---
- name: create swap
  become: yes
  command: fallocate -l 1G /swapfile
  args:
    creates: /swapfile

- name: set swap permissions
  become: yes
  file:
    path: /swapfile
    mode: 0600

- name: check swap format
  become: yes
  command: file /swapfile | grep "swap file"
  register: format_result

- name: format swap
  become: yes
  command: mkswap /swapfile
  when: format_result is failed

- name: check swap enabled
  become: yes
  command: swapon -s | grep "/swapfile"
  register: enabled_result

- name: enable swap
  become: yes
  command: swapon /swapfile
  when: enabled_result is failed

- name: update fstab
  become: yes
  mount:
    path: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
