---
- name: Create swap
  command: fallocate -l {{ swap_size }} {{ swap_path }}
  args:
    creates: "{{ swap_path }}"

- name: Set swap permissions
  file:
    path: "{{ swap_path }}"
    mode: 0600

- name: Check swap format
  command: file {{ swap_path }} | grep "swap file"
  changed_when: false
  register: format_result

- name: Format swap
  command: mkswap {{ swap_path }}
  when: format_result is failed

- name: Check swap enabled
  command: swapon -s | grep "{{ swap_path }}"
  changed_when: false
  register: enabled_result

- name: Enable swap
  command: swapon {{ swap_path }}
  when: enabled_result is failed

- name: Update fstab
  mount:
    path: none
    src: "{{ swap_path }}"
    fstype: swap
    opts: sw
    state: present
