---
- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: sievec_sieve
  command: sievec /var/lib/dovecot/sieve

- name: sievec_sieve_before
  command: sievec /var/lib/dovecot/sieve_before.d
