---
- name: purge awscli package
  apt:
    name: awscli
    state: absent
    purge: true

- name: install pip
  apt:
    name: python-pip

- name: pip install awscli
  pip:
    name: awscli

- name: manage ~/.aws directory
  file:
    path: ~/.aws
    state: directory
    mode: 0755

- name: manage ~/.aws/config
  template:
    src: config.j2
    dest: ~/.aws/config
    mode: 0600

- name: manage ~/.aws/credentials
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    mode: 0600
  no_log: true
