name 'mconigliaro_unattended_upgrades'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_unattended_upgrades'
long_description 'Installs/Configures mconigliaro_unattended_upgrades'
version '0.1.0'
