---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.0.118

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_nfs_server::default]
    attributes:
      mconigliaro_nfs_server:
        exports:
          /home: '*(rw,sync,no_root_squash)'
