name 'mconigliaro_monit'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_monit'
long_description 'Installs/Configures mconigliaro_monit'
version '0.1.0'
