---
- name: format data volumes
  filesystem:
    dev: "{{item.device}}"
    fstype: "{{('fstype' in item) | ternary(item.fstype, 'ext4')}}"
  loop: "{{data_volumes}}"
  when: (ansible_mounts | json_query(query) | length) == 0
  vars:
    query: "[?mount == `{{item.path}}`]"

- name: create data volume paths
  file:
    path: "{{item.path}}"
    state: directory
  loop: "{{data_volumes}}"

- name: mount data volumes
  mount:
    path: "{{item.path}}"
    src: "{{item.device}}"
    fstype: auto
    state: mounted
  loop: "{{data_volumes}}"
