name 'mconigliaro_plex'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_plex'
long_description 'Installs/Configures mconigliaro_plex'
version '0.1.0'
