---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.0.118

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_hosts::default]
    attributes:
