name 'mconigliaro_attic'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_attic'
long_description 'Installs/Configures mconigliaro_attic'
version '0.1.0'
