---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.0.118

platforms:
  - name: ubuntu-14.04

suites:
  - name: route53
    run_list:
      - recipe[mconigliaro_apt::default] # Fix for stale apt cache
      - recipe[mconigliaro_aws::route53]
    attributes:
      mconigliaro_aws:
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        aws_default_region: <%= ENV['AWS_DEFAULT_REGION'] %>
