name 'mconigliaro_aws'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_aws'
long_description 'Installs/Configures mconigliaro_aws'
version '0.1.0'
