---
- name: install fail2ban
  apt:
    name: fail2ban

- name: configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify:
    - restart fail2ban

# This file doesn't exist in Docker and fail2ban won't start without it
- name: create /var/log/auth.log
  copy:
    dest: /var/log/auth.log
    content: ""
  when: ansible_virtualization_type == "docker"

- name: start fail2ban
  service:
    name: fail2ban
    state: started

- name: configure monit for fail2ban
  template:
    src: fail2ban.monit.j2
    dest: /etc/monit/conf.d/fail2ban
  notify:
    - restart monit
