source 'https://supermarket.chef.io'

# If we're inside a cookbook...
if File.exist?(File.join(File.dirname(__FILE__), 'metadata.rb'))

  # Fetch dependencies from the current cookbook's metadata file
  metadata

  # Build a list of cookbooks in this repository
  cookbook_root = File.dirname(File.realpath(__FILE__))
  cookbook_paths = Dir["#{cookbook_root}/*"].select { |obj| File.exist?("#{obj}/metadata.rb") }

  # Ignore some cookbooks
  cookbook_paths.reject! do |obj|
    [
      File.basename(File.dirname(__FILE__)), # the current cookbook
      'code_generator' # Only used by `chef generate cookbook` command
    ].include?(File.basename(obj))
  end

  # Tell Berkshelf where to find the cookbooks
  cookbook_paths.each do |cookbook_path|
    cookbook File.basename(cookbook_path), path: cookbook_path
  end
end
