name 'mconigliaro_sshfs'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_sshfs'
long_description 'Installs/Configures mconigliaro_sshfs'
version '0.1.0'
