---
driver:
  name: vagrant
  vagrantfiles:
    - Vagrantfile.rb

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.0.118

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_mount::default]
    attributes:
      mconigliaro_mount:
        format: ext4
        mount:
          /dev/sdb: /mnt/data
