name 'mconigliaro_netatalk'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_netatalk'
long_description 'Installs/Configures mconigliaro_netatalk'
version '0.1.0'

depends 'mconigliaro_avahi'
depends 'mconigliaro_monit'
