---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: focal
    image: ubuntu:20.04
    hostname: focal.example.com
    privileged: true
provisioner:
  name: ansible
  options:
    D: true
verifier:
  name: testinfra
