---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_mail::default]
    attributes:
      mconigliaro_mail:
        postfix:
          aliases:
            - 'root: vagrant'
