---
- name: install sysstat
  apt:
    name: sysstat

- name: configure sysstat
  template:
    src: sysstat.j2
    dest: /etc/default/sysstat
  notify:
    - restart sysstat

- name: start sysstat
  service:
    name: sysstat
    state: started
