---
- name: Install sysstat
  apt:
    name: sysstat

- name: Configure sysstat
  copy:
    src: files/sysstat
    dest: /etc/default/sysstat
  notify:
    - Restart sysstat

- name: Start sysstat
  service:
    name: sysstat
    state: started
