---
- name: install sysstat
  become: yes
  apt:
    name: sysstat

- name: start sysstat
  service:
    name: sysstat
    state: started

- name: configure sysstat
  copy:
    src: files/sysstat
    dest: /etc/default/sysstat
  notify:
    - restart sysstat
