---
- name: install avahi
  apt:
    name:
      - dbus
      - avahi-daemon
      - avahi-utils

- name: start dbus
  service:
    name: dbus
    state: started

- name: start avahi
  service:
    name: avahi-daemon
    state: started

- name: configure monit for avahi
  template:
    src: avahi.monit.j2
    dest: /etc/monit/conf.d/avahi
  notify:
    - restart monit
