---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.0.118

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_apt::default] # Fix for stale apt cache
      - recipe[mconigliaro_zsh::test]
    attributes:
