---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    image: ubuntu:18.04
    privileged: true
  - name: focal
    image: ubuntu:20.04
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
