---
- name: Converge
  hosts: all
  roles:
    - role: block_devices
  vars:
    block_devices:
      -
        file: /tmp/test0
        size: 10
        device: /dev/loop0
      -
        file: /tmp/test1
        size: 20
        device: /dev/loop1
      -
        file: /tmp/test2
        size: 30
        device: /dev/loop2
