---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ['forwarded_port', {guest: 32400, host: 32400, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mconigliaro_plexmediaserver::default]
    attributes:
