---
- name: install nginx
  apt:
    name:
      - nginx
      - libnginx-mod-http-auth-pam
      - ssl-cert

- name: allow nginx to read /etc/shadow for auth_pam
  user:
    name: www-data
    groups:
      - shadow
    append: true
  notify:
    - restart nginx

- name: configure nginx
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/nginx/snippets/{{ item }}.conf"
    mode: 0644
  loop:
    - auth_params
    - proxy_params
    - ssl_params
  notify:
    - reload nginx

- name: configure nginx default site
  template:
    src: default.site.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  notify:
    - reload nginx

- name: delete default index.html
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: manage index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: start nginx
  service:
    name: nginx
    state: started

- name: configure monit for nginx
  template:
    src: nginx.monit.j2
    dest: /etc/monit/conf.d/nginx
  notify:
    - restart monit
