name 'mconigliaro_mutt'
maintainer 'Mike Conigliaro'
maintainer_email 'mike@conigliaro.org'
license 'all_rights'
description 'Installs/Configures mconigliaro_mutt'
long_description 'Installs/Configures mconigliaro_mutt'
version '0.1.0'
