---
- hosts: mail
  become: true
  roles:
    - swap
    - hosts
    - apt
    - packages
    - unattended_upgrades
    - sysstat
    - monit
  vars:
    hosts_domain: ec2.local
    monit_mail_format_from: monit@mail.conigliaro.org
