---
- hosts: nas
  become: true
  roles:
    - swap
    - hosts
    - apt
    - packages
    - unattended_upgrades
    - sysstat
    - monit
    - grub
    - ntp
    - rsyslog
    - openssh
    - postfix
    - mutt
    - sudo
    - fail2ban
    - raid_devices
    - data_volumes
    - users
    - route53_update_dns
    - smartmontools
    - vsftpd
    - samba
    - plexmediaserver
  vars:
    awscli_aws_access_key_id: "{{ vault_awscli_aws_access_key_id }}"
    awscli_aws_secret_access_key: "{{ vault_awscli_aws_secret_access_key }}"
    data_volumes:
      -
        device: /dev/md127
        path: /mnt/data
    monit_mail_format_from: monit@home.conigliaro.org
    postfix_conf_myhostname: home.conigliaro.org
    postfix_conf_relayhost: "[email-smtp.us-east-1.amazonaws.com]:587"
    postfix_conf_alias_maps:
      - "root: mike@conigliaro.org"
      - "mike: mike@conigliaro.org"
    postfix_conf_sasl_password_maps: "{{ vault_postfix_conf_sasl_password_maps }}"
    raid_devices:
      -
        device: /dev/md127
        raid_level: 1
        volumes:
          - /dev/sdb
          - /dev/sdc
    route53_update_dns_args: "home conigliaro.org."
    users_home_root: /mnt/data
    users_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2h1LDWTcKTAGGky45old7S+O+iKAgcz9sUGTEKnWrOp0Rtia+UG2FXWpvFWdfbM7j8jiPWZy4kqmOoPAj6E51E2B6w4G1JGXIghaUGF4DF9oFi+iim7ToTGUDIdsrpx8e/ZfWxbqP7UWqMniU6GihUW5nVZxfMcVi5N50TVaFkR4P3gw6Gf4xElZ3nDMSRzRpUJxiUpQyrno1tkGE+EQYvtPSgKFyDpEhShc/ym0RT75lxvLHWuzJfIinE3ub93YtNj0Xt0kldRULXCsyPsv5doclZiZ+Vaa0gK97i4zfWWI6pjMuvHd8oP8Nhm3eI8VD4C1P1woGZQI//QQ8JfjH mike@conigliaro.org
