---
- hosts: nas
  become: true
  roles:
    - swap
    - hosts
    - apt
    - packages
    - unattended_upgrades
    - sysstat
    - monit
    - grub
  vars:
    monit_mail_format_from: monit@home.conigliaro.org
