---
- hosts: nas
  become: true
  roles:
    - swap
    - hosts
    - apt
    - packages
    - unattended_upgrades
    - sysstat
    - monit
    - grub
    - ntp
    - rsyslog
    - openssh
    - postfix
    - mutt
    - sudo
    - fail2ban
    - raid_devices
  vars:
    monit_mail_format_from: monit@home.conigliaro.org
    postfix_conf_myhostname: home.conigliaro.org
    postfix_conf_relayhost: "[email-smtp.us-east-1.amazonaws.com]:587"
    postfix_conf_alias_maps:
      - "root: mike@conigliaro.org"
      - "mike: mike@conigliaro.org"
    postfix_conf_sasl_password_maps: "{{ vault_postfix_conf_sasl_password_maps }}"
    raid_devices:
      -
        device: /dev/md127
        raid_level: 1
        volumes:
          - /dev/sdb
          - /dev/sdc
