---
- hosts: nas
  become: true
  roles:
    - grub
    - raid_devices
    - data_volumes
    - postfix
    - route53_update_dns
    - smartmontools
    - vsftpd
    - samba
    - plexmediaserver
    - borgbackup
