---
- hosts: nas
  become: true
  roles:
    - swap
    - hosts
    - apt
    - packages
    - unattended_upgrades
    - sysstat
    - monit
    - grub
    - ntp
    - rsyslog
    - openssh
    - postfix
    - mutt
    - sudo
    - fail2ban
    - raid_devices
    - data_volumes
    - users
    - route53_update_dns
    - smartmontools
    - vsftpd
    - samba
    - plexmediaserver
