---
- name: manage debconf
  template:
    src: 70debconf.j2
    dest: /etc/apt/apt.conf.d/70debconf

- name: run apt update
  apt:
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: run apt upgrade
  apt:
    upgrade: "yes"
  when: apt_upgrade

# Required by apt-key commands
- name: install gpg
  apt:
    name: gnupg2
