---
- name: manage apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: run apt update
  apt:
    cache_valid_time: 86400

- name: install debconf-utils
  apt:
    name: debconf-utils

- name: manage debconf
  template:
    src: 70debconf.j2
    dest: /etc/apt/apt.conf.d/70debconf

- name: run apt upgrade
  apt:
    upgrade: yes
  # FIXME: Why is Ansible warning about this being a string?
  when: apt_upgrade

# Required by apt-key commands
- name: install gpg
  apt:
    name: gnupg2
