---
- name: Manage apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  notify:
    - Run apt update

- name: Run apt update immediately
  meta: flush_handlers

- name: Install debconf-utils
  apt:
    name: debconf-utils

- name: Manage debconf
  template:
    src: 70debconf.j2
    dest: /etc/apt/apt.conf.d/70debconf

- name: Run apt upgrade
  apt:
    upgrade: true
  when: apt_upgrade

# Required by apt-key commands
- name: Install gpg
  apt:
    name: gnupg2
