---
- name: restart redis
  service:
    name: redis-server
    state: restarted

- name: restart sysfsutils
  service:
    name: sysfsutils
    state: restarted
  when: ansible_virtualization_type != 'docker'

- name: reload systemd
  systemd:
    daemon_reload: yes
