---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: Configure unattended-upgrades
  template:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
