---
- name: install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: configure unattended-upgrades
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
