---
- name: add certbot key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 75BCA694

- name: add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot

- name: install ssl-cert
  apt:
    name: ssl-cert

- name: manage SSL certificate directory permissions
  file:
    path: /etc/ssl/private
    group: ssl-cert
    recurse: true

# FIXME: package not available in focal yet
- name: install certbot
  apt:
    name: certbot

- name: install certbot plugins
  apt:
    name: "{{ certbot_plugins }}"

- name: configure certbot CLI
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini

- name: manage renewal hooks permissions
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    mode: 0755
    recurse: true

- name: configure cert permissions renewal hook
  template:
    src: 50-permissions.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/50-permissions
    mode: 0755
  notify: fix cert permissions

- name: fix cert permissions immediately
  meta: flush_handlers

- name: run certbot
  command: certbot {{ certbot_options | join(' ') }} --non-interactive --quiet
  # It looks like certbot doesn't run the renewal hooks on initial cert creation (only renewal)
  notify: fix cert permissions
  when: certbot_options | length > 0
