---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: ubuntu:16.04
    hostname: xenial.example.com
  - name: focal
    image: ubuntu:20.04
    hostname: focal.example.com
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    D: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
