---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial.example.com
    image: ubuntu:16.04
  - name: focal.example.com
    image: ubuntu:20.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    D: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
