---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    image: ubuntu:18.04
    hostname: bionic.example.com
  - name: focal
    image: ubuntu:20.04
    hostname: focal.example.com
provisioner:
  name: ansible
  options:
    D: true
verifier:
  name: testinfra
