---
- name: Converge
  hosts: all
  roles:
    - role: rspamd
    - role: postfix
  vars:
    postfix_conf_mailbox_transport: lmtp:unix:private/dovecot-lmtp
    postfix_conf_smtpd_milters: inet:127.0.0.1:11332
    postfix_configure_smtpd_sasl: true

    postfix_conf_alias_maps:
      - "test: mike"
    postfix_conf_sasl_password_maps:
      - username password
    postfix_conf_virtual_maps:
      - test@example.com test
