---
- name: Converge
  hosts: all
  roles:
    - role: postfix
  vars:
    postfix_configure_dovecot_lmtp: true
    postfix_configure_rspamd: true
    postfix_configure_smtpd_sasl: true

    postfix_conf_alias_maps:
      - "test: mike"
    postfix_conf_sasl_password_maps:
      - username password
    postfix_conf_virtual_maps:
      - test@example.com test
